services:
  web:
    build: .
    container_name: web
    command: gunicorn --timeout 300 config.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - config/.env
    volumes:
      - .:/app

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - /etc/letsencrypt/live/thewolfanalytics.uz/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/thewolfanalytics.uz/privkey.pem:/etc/nginx/certs/privkey.pem
      - static_volume:/app/static/
      - media_volume:/app/static/media/
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local